language: python
python:
    - "3.4"
env:
    - FLASK_CONFIG="../conf/dev.py"
install:
    - "pip install six"
    - "pip install -r requirements.txt -r requirements-dev.txt"
    - "pip install coveralls pep8"
script: 'py.test --cov atlas_core --cov-report term-missing atlas_core/tests.py'
after_success:
    coveralls -v
